/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangAboutRouteImport } from './routes/$lang.about'
import { Route as LangContactRouteImport } from './routes/$lang.contact'
import { Route as LangPressRouteImport } from './routes/$lang.press'
import { Route as LangArtistsIndexRouteImport } from './routes/$lang.artists.index'
import { Route as LangArtistsArtistIdRouteImport } from './routes/$lang.artists.$artistId'
import { Route as LangProjectsIndexRouteImport } from './routes/$lang.projects.index'
import { Route as LangProjectsProjectIdRouteImport } from './routes/$lang.projects.$projectId'
import { Route as LangPublicationsIndexRouteImport } from './routes/$lang.publications.index'
import { Route as LangPublicationsPublicationIdRouteImport } from './routes/$lang.publications.$publicationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangPressRoute = LangPressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => LangRoute,
} as any)
const LangArtistsIndexRoute = LangArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => LangRoute,
} as any)
const LangArtistsArtistIdRoute = LangArtistsArtistIdRouteImport.update({
  id: '/artists/$artistId',
  path: '/artists/$artistId',
  getParentRoute: () => LangRoute,
} as any)
const LangProjectsIndexRoute = LangProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => LangRoute,
} as any)
const LangProjectsProjectIdRoute = LangProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => LangRoute,
} as any)
const LangPublicationsIndexRoute = LangPublicationsIndexRouteImport.update({
  id: '/publications/',
  path: '/publications/',
  getParentRoute: () => LangRoute,
} as any)
const LangPublicationsPublicationIdRoute =
  LangPublicationsPublicationIdRouteImport.update({
    id: '/publications/$publicationId',
    path: '/publications/$publicationId',
    getParentRoute: () => LangRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/press': typeof LangPressRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/artists/$artistId': typeof LangArtistsArtistIdRoute
  '/$lang/projects/$projectId': typeof LangProjectsProjectIdRoute
  '/$lang/publications/$publicationId': typeof LangPublicationsPublicationIdRoute
  '/$lang/artists/': typeof LangArtistsIndexRoute
  '/$lang/projects/': typeof LangProjectsIndexRoute
  '/$lang/publications/': typeof LangPublicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/press': typeof LangPressRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/artists/$artistId': typeof LangArtistsArtistIdRoute
  '/$lang/projects/$projectId': typeof LangProjectsProjectIdRoute
  '/$lang/publications/$publicationId': typeof LangPublicationsPublicationIdRoute
  '/$lang/artists': typeof LangArtistsIndexRoute
  '/$lang/projects': typeof LangProjectsIndexRoute
  '/$lang/publications': typeof LangPublicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/press': typeof LangPressRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/artists/$artistId': typeof LangArtistsArtistIdRoute
  '/$lang/projects/$projectId': typeof LangProjectsProjectIdRoute
  '/$lang/publications/$publicationId': typeof LangPublicationsPublicationIdRoute
  '/$lang/artists/': typeof LangArtistsIndexRoute
  '/$lang/projects/': typeof LangProjectsIndexRoute
  '/$lang/publications/': typeof LangPublicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/press'
    | '/$lang/'
    | '/$lang/artists/$artistId'
    | '/$lang/projects/$projectId'
    | '/$lang/publications/$publicationId'
    | '/$lang/artists/'
    | '/$lang/projects/'
    | '/$lang/publications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/press'
    | '/$lang'
    | '/$lang/artists/$artistId'
    | '/$lang/projects/$projectId'
    | '/$lang/publications/$publicationId'
    | '/$lang/artists'
    | '/$lang/projects'
    | '/$lang/publications'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/press'
    | '/$lang/'
    | '/$lang/artists/$artistId'
    | '/$lang/projects/$projectId'
    | '/$lang/publications/$publicationId'
    | '/$lang/artists/'
    | '/$lang/projects/'
    | '/$lang/publications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/press': {
      id: '/$lang/press'
      path: '/press'
      fullPath: '/$lang/press'
      preLoaderRoute: typeof LangPressRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/artists/': {
      id: '/$lang/artists/'
      path: '/artists'
      fullPath: '/$lang/artists/'
      preLoaderRoute: typeof LangArtistsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/artists/$artistId': {
      id: '/$lang/artists/$artistId'
      path: '/artists/$artistId'
      fullPath: '/$lang/artists/$artistId'
      preLoaderRoute: typeof LangArtistsArtistIdRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/projects/': {
      id: '/$lang/projects/'
      path: '/projects'
      fullPath: '/$lang/projects/'
      preLoaderRoute: typeof LangProjectsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/projects/$projectId': {
      id: '/$lang/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/$lang/projects/$projectId'
      preLoaderRoute: typeof LangProjectsProjectIdRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/publications/': {
      id: '/$lang/publications/'
      path: '/publications'
      fullPath: '/$lang/publications/'
      preLoaderRoute: typeof LangPublicationsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/publications/$publicationId': {
      id: '/$lang/publications/$publicationId'
      path: '/publications/$publicationId'
      fullPath: '/$lang/publications/$publicationId'
      preLoaderRoute: typeof LangPublicationsPublicationIdRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangContactRoute: typeof LangContactRoute
  LangPressRoute: typeof LangPressRoute
  LangIndexRoute: typeof LangIndexRoute
  LangArtistsArtistIdRoute: typeof LangArtistsArtistIdRoute
  LangProjectsProjectIdRoute: typeof LangProjectsProjectIdRoute
  LangPublicationsPublicationIdRoute: typeof LangPublicationsPublicationIdRoute
  LangArtistsIndexRoute: typeof LangArtistsIndexRoute
  LangProjectsIndexRoute: typeof LangProjectsIndexRoute
  LangPublicationsIndexRoute: typeof LangPublicationsIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangContactRoute: LangContactRoute,
  LangPressRoute: LangPressRoute,
  LangIndexRoute: LangIndexRoute,
  LangArtistsArtistIdRoute: LangArtistsArtistIdRoute,
  LangProjectsProjectIdRoute: LangProjectsProjectIdRoute,
  LangPublicationsPublicationIdRoute: LangPublicationsPublicationIdRoute,
  LangArtistsIndexRoute: LangArtistsIndexRoute,
  LangProjectsIndexRoute: LangProjectsIndexRoute,
  LangPublicationsIndexRoute: LangPublicationsIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
